### ISSUE TITLE
Something wrong with running example

### ISSUE THREAD

**Issue by galstriker** [pianpianyouche/plascad#1]
Hi, @pianpianyouche 
I found this software and I couldn't help trying it. I installed this software using conda. However, when I ran with the example fasta file, it reported that something was wrong:
~~~
 Error: Sequence file /mnt/d/test2/example_MOB_temp_mob.faa is empty or misformatted

cat: '*ATPase.hmm_domtblout_parsed_out': No such file or directory
cat: '*T4CP*_domtblout_parsed_out': No such file or directory
cat: '/mnt/d/test2/example*MPFF*_result_out': No such file or directory
cat: '/mnt/d/test2/example*MPFG*_result_out': No such file or directory
cat: '/mnt/d/test2/example*MPFI*_result_out': No such file or directory
cat: '/mnt/d/test2/example*MPFT*_result_out': No such file or directory
Warning: [blastp] Number of threads was reduced to 8 to match the number of available CPUs
~~~
I updated the software with conda but the issue was still there. Could you help me? Thanks.

**Comment by pianpianyouche** [comment]
Hi galstriker,
Thank you for your feedback. I just tried it and it worked for me.
Did you install it with the following commend? 
conda create -n Plascad -y -c bioconda -c pianpianyouche plascad
conda activate Plascad
does "Plascad -h" work for you after installation?

**Comment by pianpianyouche** [comment]
> Hi, @pianpianyouche
> I found this software and I couldn't help trying it. I installed this software using conda. However, when I ran with the example fasta file, it reported that something was wrong:
> 
> ```
>  Error: Sequence file /mnt/d/test2/example_MOB_temp_mob.faa is empty or misformatted
> 
> cat: '*ATPase.hmm_domtblout_parsed_out': No such file or directory
> cat: '*T4CP*_domtblout_parsed_out': No such file or directory
> cat: '/mnt/d/test2/example*MPFF*_result_out': No such file or directory
> cat: '/mnt/d/test2/example*MPFG*_result_out': No such file or directory
> cat: '/mnt/d/test2/example*MPFI*_result_out': No such file or directory
> cat: '/mnt/d/test2/example*MPFT*_result_out': No such file or directory
> Warning: [blastp] Number of threads was reduced to 8 to match the number of available CPUs
> ```
> 
> I updated the software with conda but the issue was still there. Could you help me? Thanks.
